### ISSUE TITLE
Feature request: authentication

### ISSUE THREAD

**Issue by diroru** [andrejewski/smithsonian#3]
Hello,
first of all, thanks for the great plugin!

As you may have already guessed, i am looking for a way to have some protection around the web interface. Maybe it exceeds the scope of the project?

Your insights would be greatly appreciated!

Cheers,
dimitar

**Comment by andrejewski** [comment]
Authentication is out of the scope of this project, but it is quite easily to have any authentication mechanism you desire in front of Smithsonian. Any Express compatible middleware will do, such as [basic auth](https://github.com/jshttp/basic-auth). See `Smithsonian.router()` for using Smithsonian inside of Express applications.

**Comment by diroru** [comment]
Thanks a lot, duly noted & much appreciated!
