### ISSUE TITLE
Hello, Im getting an error : cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by abhijeetvramgir** [andrejewski/smithsonian#5]
Hello, I'm trying to use run this:
var Smithsonian = require('smithsonian');
Smithsonian(__dirname).listen(3000);

Im getting this error:
Error: Cannot find module 'mkdirp'

Any help?
Thanks!

**Comment by andrejewski** [comment]
Will fix, please hold.

**Comment by abhijeetvramgir** [comment]
Thanks so much!

**Comment by andrejewski** [comment]
This is fixed in `3.0.1` please reinstall this new version.
